version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm i

      - run:
          name: Install Prettier
          command: npm i -g prettier

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: prettier --write .

      - run:
          name: Build
          command: npm run build
